joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50  

right_rear_velocity_controller:
  type: "velocity_controllers/JointVelocityController"
  joint: right_rear_wheel_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}
left_rear_velocity_controller:
  type: "velocity_controllers/JointVelocityController"
  joint: left_rear_wheel_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}
# right_bridge_position_controller:
#   type: "effort_controllers/JointPositionController"
#   joint: right_bridge_to_bridge
#   pid: {p: 40.0, i: 0.0, d: 1.0}
# left_bridge_position_controller:
#   type: "effort_controllers/JointPositionController"
#   joint: left_bridge_to_bridge
#   pid: {p: 40.0, i: 0.0, d: 1.0}
